### ISSUE TITLE
Create 'Who ...?' logs

### ISSUE THREAD

**Issue by arsley** [arsley/Ordering-system#7]
_誰がどんなことをした_ かを単純なログ形式でみられるようなページを作る。

**Comment by assly** [comment]
`Employee`、`Log`テーブルを作る。

## Employee

`fullname` *string*|`username` *string*|`password_digest` *string*
-|-|-
`Mr. User`|`user`|`329435e5e66be809a656af105f42401e`

## Log

`who` *string*|`done` *string*
-|-
`Dr. User`|`患者〇〇にオーダー#△△を作成しました`
`Dr. User`|`オーダー#△△に検査を追加しました`
`Dr. User`|`オーダー#△△をキャンセルしました`
`Dr. User`|`オーダー#△△の検査に変更があります`

### 通知の仕様(仮)

- 作成（new, create）通知はオーダー毎に行う
  - 「患者〇〇にオーダー#△△が作成されました」
  - オーダーに付随して作成される検査は多数なので、それらについては通知しない
- 既存のオーダーに新しく検査を作成した場合は通知する
  - 「オーダー#△△に検査が追加されました」
- 変更（edit, update）通知はオーダーおよび検査毎に行う
  - 「オーダー #△△がキャンセルされました / オーダー #△△の検査に変更があります」

**Comment by assly** [comment]
`Employees`に`has_many :logs`として、`/employees/:id (employees#show)`で「直近の作業ログ」みたいなものが出せたら便利かも？

**Comment by assly** [comment]
#8

**Comment by assly** [comment]
`GET /`ページでとりあえず「直近10件の通知」みたいなものを出すつもり。

**Comment by assly** [comment]
`オーダー#△△`をリンクにできた方がアクセスしやすいと思うので、テーブルの構造を変える。

`who` *string*|`done` *string*|`order_id *integer*`
-|-|-
`Dr. User`|`患者〇〇にオーダー#△△を作成しました`|`1`
`Dr. User`|`オーダー#△△に検査を追加しました`|`1`
`Dr. User`|`オーダー#△△をキャンセルしました`|`1`
`Dr. User`|`オーダー#△△の検査を変更しました`|`1`

`Order has_many :logs`にするかは一考の余地あり?
- 作業ログ（記録）であるという設計上、関連させてもそんなに意味がない気もする

**Comment by assly** [comment]
## 案 updated

`Employee has_many :logs`

### Log table

`employee_id` *belongs_to*|`done` *string*|`order_id` *integer*
-|-|-
`1`|`患者〇〇に__を作成しました`|`1`
`1`|`__に検査を追加しました`|`1`
`1`|`__をキャンセルしました`|`1`
`1`|`__の検査を変更しました`|`1`

### Render helper

```ruby
# application_helper.rb

def render_log(log)
  log.done.sub('__', link_to("オーダー#{log.order_id}", order_inspections_path(order_id)))
end
```

**Comment by assly** [comment]
82d1f3d5038dc16292f3de0ad9283d08715be87c
