### ISSUE TITLE
Create notification

### ISSUE THREAD

**Issue by arsley** [arsley/Ordering-system#8]
通知機能を作る。
現時点では厳密な仕様がないためそこから考えていきたい...

**Comment by assly** [comment]
## 使えそうなやつ

- [RPush](https://github.com/rpush/rpush)
- [RailsからRPushを使う](http://famtom.hatenablog.com/entry/2014/09/09/184220)

**Comment by assly** [comment]
## 参考になりそうなやつ
- [Using VAPID for Web push notification](https://medium.com/seed-digital/using-vapid-for-web-push-notifications-in-a-ruby-on-rails-application-e8e3ae00ab50)

**Comment by arsley** [comment]
どの程度の通知が必要かは不明だが、 #20 で各従業員の作業ログを出力（確認）できるようにした。

**Comment by arsley** [comment]
これも良さそう。[Onesignal](https://onesignal.com/)

**Comment by arsley** [comment]
[How to add real web push notifications to your webapp - A geek with a hat](https://swizec.com/blog/add-real-web-push-notifications-webapp/swizec/7924)

**Comment by arsley** [comment]
7efd34d3175cc1327f6a007fba94766a798918b7
それなりの機能は作成したものの、ServiceWorkerがtest環境では正しく動作しないため、fixtureなどで代替する必要がある。

**Comment by arsley** [comment]
98539571cc2f8b8a7f30b6abb96ce02a108cdfa0
MockModuleを作って解決した。

**Comment by arsley** [comment]
[Sending Web Push Notifications with OneSignal and Ruby on Rails · Sweetcode.io](https://sweetcode.io/web-push-notifications-onesignal-ruby-rails/)

これを試します。
